# Generated by Django 4.1.7 on 2023-03-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AquaPlants', to='aquaworld.aquariums')),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substrate', models.CharField(default='', max_length=80)),
                ('base', models.CharField(default='', max_length=80)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AquaGround', to='aquaworld.aquariums')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AquaFish', to='aquaworld.aquariums')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('dose', models.FloatField(default=0)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AquaFert', to='aquaworld.aquariums')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting', models.CharField(default='', max_length=100)),
                ('filtering', models.CharField(default='', max_length=80)),
                ('heating', models.CharField(default='', max_length=60)),
                ('CO2', models.CharField(default='', max_length=150)),
                ('control', models.CharField(default='', max_length=100)),
                ('other', models.CharField(default='', max_length=150)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AquaEquipment', to='aquaworld.aquariums')),
            ],
        ),
    ]
