# Generated by Django 4.1.7 on 2023-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0002_plants_ground_fish_fertilization_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='CO2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='control',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='other',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='ground',
            name='base',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ground',
            name='substrate',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
