# Generated by Django 4.1.7 on 2023-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0004_alter_fish_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fertilization',
            unique_together={('aquarium', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='plants',
            unique_together={('aquarium', 'name')},
        ),
    ]
