# Generated by Django 4.1.7 on 2023-03-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0005_alter_fertilization_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='aquarium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AquaEquipment', to='aquaworld.aquariums'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='aquarium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AquaGround', to='aquaworld.aquariums'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='/profile/Avatar.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='province',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
