# Generated by Django 4.1.7 on 2023-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0006_alter_equipments_aquarium_alter_ground_aquarium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilization',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plants',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='profile/Avatar.png', upload_to='profile/'),
        ),
    ]
