# Generated by Django 4.1.7 on 2023-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0007_fertilization_is_editing_fish_is_editing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquariums',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
    ]
