# Generated by Django 4.1.7 on 2023-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0008_aquariums_is_editing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquariums',
            name='is_editing',
        ),
        migrations.RemoveField(
            model_name='fertilization',
            name='is_editing',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='is_editing',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='is_editing',
        ),
    ]
