# Generated by Django 4.1.7 on 2023-04-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0014_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_push_token',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_push_token',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
