# Generated by Django 4.1.7 on 2023-04-04 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0016_alter_user_push_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='requested_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
