# Generated by Django 4.1.7 on 2023-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0018_alter_comments_user_alter_posts_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_push_token',
            name='token',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
