# Generated by Django 4.1.7 on 2023-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaworld', '0019_alter_user_push_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_push_token',
            name='token',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
